### ISSUE TITLE
[Server]: Change tcp-interface to work with JSON and incorporate into debug page

### ISSUE THREAD

**Issue by xXDMOGXx** [Comet-Robotics/chessBot#121]
#### Task Description:
tcp-interface is currently using a raw data stream that must be parsed. It needs to be changed to use JSON instead to allow ease of use and expansion. It also needs to be incorporated into the debug page to allow robot manual control

1. Adding bot tunnels will need to read the mac from a JSON
2.  Send a serialized JSON as a message over the tunnel when communicating with bots
The PacketType will be named `type` in the JSON

**Comment by democat3457** [comment]
Duplicate of #101
