### ISSUE TITLE
[Client]: Debug page UI should be updated

### ISSUE THREAD

**Issue by Kandles11** [Comet-Robotics/chessBot#137]
#### Task Description:
Right now, the debug page is a vertical list of elements that looks really funky. It should be rearranged so it has a more appropriate layout.

Something like below would look better:
```
|      [ ]      |
|  [ ] [ ] [ ]  |
|  [   STOP  ]  |
```
Where the brackets represent the buttons and the lines represent the power levels.

**Comment by harsh2226** [comment]
Haven't been able to work on it since last meeting, hopefully get progress done upcoming weekend.
