### ISSUE TITLE
[Server]: Create move classification methods in Chess Engine

### ISSUE THREAD

**Issue by xXDMOGXx** [Comet-Robotics/chessBot#146]
#### Task Description: 
When generating commands, we need to check certain conditions that will cause special logic. These conditions will have methods in `src/common/chess-engine.ts` that can be called.

#### Implementation Steps:
We will need a method called getPieceType that takes in a `Move`, and returns the `PieceType` enum of the piece that is initiating a move. (Both PieceType and Move are located in `src/common/game-types.ts`)
We will also need a series of checking methods. All of these methods will take in a `Move`, and return a boolean.
These are the methods that need to be implemented:
- **isPromoting**: Checks whether a move results in the promotion of a pawn. This should simply be checking whether `promotionPiece` is present on the move.
- **isKingSideCastling**: Checks whether a move is a [castle](https://support.chess.com/en/articles/8557430-how-do-i-castle) on the King's side of the board. Don't forget to verify the castling rights are allowed via `chess.js`. 
- **isQueenSideCastling**: Checks whether a move is a castle on the Queen's side of the board
- **isEnPassant**: Checks whether a move involves a pawn capturing specifically via [En passant](https://en.wikipedia.org/wiki/En_passant). This should just be checking whether a pawn move is diagonal and onto an unoccupied square.
- **isCapturing**: Checks whether a move involves the initiating piece capturing another piece (Make sure to handle en passant. You can just call your isEnPassant method to check this so you don't have to duplicate logic).

#### Additional Notes and Resources:
A lot of this information can be gathered from `src/common/game-types.ts` or from the chess.js instance in `src/common/chess-engine.ts`

#### Expected Timeline:
This should be able to be completed with a single ChessBot meeting.

If you have any questions while working on this task, don't hesitate to do any one of the following:

-   Ask a lead at a meeting
-   Post in Discord
-   Reply to this issue

**Comment by MuditUpadhyay04** [comment]
Due to assignments, midterm 2 and my new on-campus job I haven't been able to work on this. I will get on this as soon as my schedule opens back up tomorrow.

**Comment by xXDMOGXx** [comment]
Hey, there hasn't been any progress since you last gave an update. I'm going to remove you from this since it's become high priority. If it sits unfinished for a couple days, you can request to be added back on
