### ISSUE TITLE
classifyMove Function

### ISSUE THREAD

**Issue by AlexKempen** [Comet-Robotics/chessBot#41]
We need a function which computes properties of a given move. This will eventually be used as the first step in the pipeline of converting a move in the frontend into commands for robots to drive - in particular, it tells us which pattern we're currently executing.

1. Create an interface (or a class?), `Move`, which has the following properties:
An enum named `MoveType` saying the type of move:
LINEAR, (i.e. horizontal or vertical shift)
DIAGONAL,
KNIGHT,
CASTLE
A boolean named capture which says whether the move is a capture.

2. Write a function named `classifyMove` which takes two `Square`s and a `PieceManager` as arguments and returns a Move. 
You may assume the move is valid; if it is not, you should throw an error.

3. Talk to Alex and/or Colin about writing tests for your function.

**Comment by xXDMOGXx** [comment]
Ticket is now in draft until it is updated to fit the task request format, or is finished
