### ISSUE TITLE
RobotSocket implementation

### ISSUE THREAD

**Issue by democat3457** [Comet-Robotics/chessBot#45]
[`RobotSocket`](https://github.com/Comet-Robotics/chessBot/blob/main/src/server/robot/robotsocket.ts) is an object of the Robot that abstracts robot calls into TCP messages that interface with the physical robot. To accomplish this, you will need to port code from the old implementation of the chess bot server, from which the connection manager can be found in [BotServer.js @ commit `263e34`](https://github.com/Comet-Robotics/chessBot/blob/263e34affd7d03fb54ba061efd2c0ad32cc3bb32/webServer/include/BotServer.js). The `drive` and `turn` methods should be implemented, and any other pertinent messages to or from the robot should be exposed as public functions as well. The RobotSocket should also handle reconnecting to a robot if connection is lost.

**Comment by xXDMOGXx** [comment]
Ticket is now in draft until it is updated to fit the task request format, or is finished
