### ISSUE TITLE
Authentication endpoint

### ISSUE THREAD

**Issue by democat3457** [Comet-Robotics/chessBot#46]
The authentication endpoint on the server, which should be located at `/auth`, will handle client join requests.

When a client joins for the first time, the server will send a randomly generated unique id (UUID) back to the client as a cookie, identifying that client with the UUID. Subsequent joins by that client will have the UUID cookie attached, allowing the server to parse the UUID and identify the same client. The client behavior around cookies will be handled automatically by the browser; the server just needs to send the UUID as a cookie, and it can assume it will get sent back in all future requests.

This UUID will allow the server to identify players in a game and ensure other people cannot join the ongoing game, either concurrently or if one of the players loses connection. The cookie aspect is especially important to this regard, because the server needs to be able to identify which connecting client is the correct one to put into the game.

The implementation required by this issue should just handle `/auth` requests, as well as generation and handling of UUID cookies. When the server receives a join request, it will check if a UUID cookie is present: if the cookie is present, it will use that UUID; otherwise, the server will generate a new UUID. The UUID retrieved, whether parsed or generated, should be sent back to the client as a cookie. *Game- or player-related features will be implemented later.*

**Comment by Kandles11** [comment]
i have created the endpoint, and it handles very basic cookie handling for now. planning on working on it further to add the UUID generation, but the basic idea should be there and is working.
