### ISSUE TITLE
Implement relativeMove on Robot

### ISSUE THREAD

**Issue by AlexKempen** [Comet-Robotics/chessBot#51]
We should implement the relativeMove method of robot. The method should cause the robot to turn and drive to a relative point. The easiest way to implement is likely to call Robot's `absoluteTurn` and then chain on a call to RobotSocket's `drive` (using `.then` to chain the promise returned by `absoluteTurn`). 

Any implementation should also include tests in `robot.test.ts`. If you want to experience the joys of Test Driven Development, write the tests first before modifying any code in robot.

**Comment by xXDMOGXx** [comment]
Ticket is now in draft until it is updated to fit the task request format, or is finished
