### ISSUE TITLE
Add Support for Multiple Clients

### ISSUE THREAD

**Issue by AlexKempen** [Comet-Robotics/chessBot#60]
We should be able to tweak the UI and server code to support game play between multiple clients.

This should be doable by checking the clientId of `req` in the `websocketHander`. When sockets are first created, it probably makes sense to assign the first connection as the host, and the second as the other player. As the clients are connected, we can harvest the instances of `ws` and store them externally. We can then use those instances to enable back and forth play between the two clients.

**Comment by AlexKempen** [comment]
Flow:
When clients first connect, they're in a setup phase. 
Initial client connection could be a couple different things: 
In a lobby (is the host?)
In a game (i.e. reconnecting)

The first client is the host and gets to dictate game settings to the server.
Then the client tells the server to begin the game.
Both clients get told the game is beginning and their color. - (can this be abstracted to connecting to a game?)
The white client makes a move. The move is sent on to the black client.
Play continues until a move is mate or the game is otherwise over. The server sends both clients a game over message with the result of the game.
The host can then send the clients back to the lobby or start a new game or something.

**Comment by xXDMOGXx** [comment]
Ticket is now in draft until it is updated to fit the task request format, or is finished
