### ISSUE TITLE
[Client]: Manual Controller UI

### ISSUE THREAD

**Issue by AlexKempen** [Comet-Robotics/chessBot#65]
#### Task Description:
We need to implement a manual controller for robots in the UI. This should consist of buttons to turn left and right and drive forward and backwards.

This could also be implemented as a joystick element

We could also potentially find a d-pad react component to use.

#### Implementation Steps:
1. Create a Components folder in the client directory to store React components
2. Create or implement the react component. 
3. Logic will be needed to convert input to data suitable for robot control (can reference old version for ideas)

Difficulties:
This issue may require a decent understanding of React to implement well.

Extra Info:
An older implementation can be found in :
`chess-bot-client/public/debug/index.html`

Relevant Links:
[Potential Joystick Component](https://www.npmjs.com/package/react-joystick-component)

Time Estimate:
Around 2 hours

If you have any questions while working on this task, post in the Programming Channel on Discord, reply to this issue on GitHub, or ask The Software Team Lead at one of our meetings.

**Comment by xXDMOGXx** [comment]
Ticket is now in draft until the it is updated to fit the task request format, or is finished
