### ISSUE TITLE
[Client]: Improve Debug UX and UI Design

### ISSUE THREAD

**Issue by xXDMOGXx** [Comet-Robotics/chessBot#68]
The debug page should initially consist of a chessboard on the left side of the screen. Instead of chess pieces, the board should show a representation of each bot in their location. Each bot will have their ID displayed as text on them.

When a bot is clicked, it should show a menu on the right of all the things we can do to it (for debug settings that effect the server or all bots, they can be always showing)
Example controls that will show when bot is clicked:
- Button to enable manual control which will show the manual control joystick
- Ability to select a packet and input values to send to the bot (Drive, Turn, Emergency Stop, etc)

**Comment by xXDMOGXx** [comment]
Another example, perhaps a log window in the bottom right (below controls and buttons) that shows the back and forth of messages between the bot and the server in real time

**Comment by AlexKempen** [comment]
We should decompose this into a bunch of smaller tickets - the debug view itself probably makes more sense as a milestone. To start with it might make sense to have a list of robots accessible on the client, probably using something like a blueprint select component alongside a server endpoint for viewing the list of robots (which is two separate tickets right there).
