### ISSUE TITLE
[Project]: Update the readme.md

### ISSUE THREAD

**Issue by AlexKempen** [Comet-Robotics/chessBot#71]
We should update the readme.md.

Steps:
1. Installation - add one-time setup instructions for vscode. This should probably include cloning from github, downloading node, adding the relevant extensions (use the vscode prompt or the `@reccomended` tag to get add the  recommended repo extensions), and any other necessary setup.
2. Development - add instructions for running tests, installing dependencies, and running the dev server in vscode using vscode tasks.
3. Project structure - give a high level overview of the various top level directories.

**Comment by xXDMOGXx** [comment]
Moving this to high priority since it's important for new people to have a clear introduction and instructions to be able to work on the project

**Comment by xXDMOGXx** [comment]
Ticket is now in draft until it is updated to fit the task request format, or is finished
