### ISSUE TITLE
[Client]: Click to move chess piece

### ISSUE THREAD

**Issue by Kandles11** [Comet-Robotics/chessBot#75]
#### Task Description:
On the Client, the user should be able to click a Chess piece, and the available spaces should be highlighted. This makes it easier for the user to use the site

Task is located in `src/client/chessboard-wrapper.tsx`

#### Implementation Steps:

1. When a chess piece is clicked, the local chess.js instance should be queried for possible moves. The possible moves should be saved in a React `useState` hook to make them available to the component.
2. The available spaces should then be shown on the chessboard using React.
- Be sure to account for situations where there may be not available moves.

#### Difficulties:
This issue may require a decent understanding of React to implement well.

#### Extra Info:
The previous implementation can be seen in the old "chess-bot-client/src/App.js"

#### Relevant Links:
`chess-bot-client/src/App.js`

#### Time Estimate: 
Around 3 hours

If you have any questions while working on this task, post in the Programming Channel on Discord, reply to this issue on GitHub, or ask The Software Team Lead at one of our meetings.

**Comment by xXDMOGXx** [comment]
Approved
