### ISSUE TITLE
[Server]: Move Chess.js to seperate class/file

### ISSUE THREAD

**Issue by Kandles11** [Comet-Robotics/chessBot#76]
#### Task Description:
This task will separate the chess.js package to its own class/file in the project. This will allow us to further abstract the engine to make it use simpler and cleaner.

#### Implementation Steps:
1. An engine folder should be created with an `engine.ts` in server
2. The chess.js engine should be imported into the new file
3. In the new file, you should reimplement the chess logic that was present in `api.ts`
4. Make sure to provide an interface between `engine.ts` and other files. (this is done with public methods in the class)
- You can write logs to verify that the chess engine is updating properly and changes are being reflected when the client updates

#### Difficulties:
- Making sure all methods necessary are implemented.
- Making sure to correctly use TypeScript syntax

#### Relevant Links:
[ChessJS Docs](https://www.npmjs.com/package/chess.js)

#### Time Estimate: 
1-2 Hours

If you have any questions while working on this task, post in the Programming Channel on Discord, reply to this issue on GitHub, or ask The Software Team Lead at one of our meetings.
- Ask Mason, Colin, Jason if extra help is needed.

**Comment by xXDMOGXx** [comment]
I'm thinking this is low difficulty low priority. Mostly just about moving some code and creating an interface

**Comment by xXDMOGXx** [comment]
approved
